name: convert_temperature
description:  U can use my temperature converter anytime it is comfortable and good works
version: 1.0.1
homepage: https://github.com/Abrorov-javohir/temperature_converter
repository: https://github.com/Abrorov-javohir/temperature_converter
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
